import { getCategories } from "@/lib/getCategories";
import { GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
interface Props {
  categories: Category[];
}

export default function index({ categories }: Props) {
  return (
    <>
      <Head>
        <title>Categories</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 px-5 md:px-10 lg:px-20 py-5 lg:py-10">
        {categories.map(({ slug, category_name, image }) => (
          <Link href={`/collections/${slug}`} key={category_name} className="border border-gray-100 shadow-sm rounded-md hover:bg-gray-50 transition">
            <Image
              src={`https://pacific-depths-48667.herokuapp.com/${image}`}
              width={400}
              height={400}
              className="object-contain w-full"
              alt={category_name}
            />
          </Link>
        ))}
      </div>
    </>
  );
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const categories = await getCategories();
  return {
    props: {
      categories,
    },
  };
};
