import SectionProduct from "@/components/SectionProduct";
import { getFeatured } from "@/lib/getFeatured";
import Head from "next/head";
import React from "react";

export default function featured({ data }: any) {
  return (
    <>
      <Head>
        <title>Featured Product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-bg">
        <SectionProduct title="Featured Product" data={data} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const data = await getFeatured();
  return {
    props: {
      data,
    },
  };
}
