import Head from "next/head";
import HomeCarousel from "@/components/HomeCarousel";
import TrendingCarousel from "@/components/TrendingCarousel";
import SectionProduct from "@/components/SectionProduct";

const images = [
  {
    id: "1",
    src: "/slideshow_5.webp",
  },
  {
    id: "2",
    src: "/slideshow_15.webp",
  },
  {
    id: "3",
    src: "/slideshow_3.webp",
  },
  {
    id: "4",
    src: "/slideshow_3.webp",
  },
  {
    id: "4",
    src: "/slideshow_3.webp",
  },
  {
    id: "6",
    src: "/slideshow_3.webp",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-bg pb-5 md:pb-10">
        <HomeCarousel images={images} />
        <TrendingCarousel images={images} />
        <SectionProduct />
      </main>
    </>
  );
}
