import Head from "next/head";
import HomeCarousel from "@/components/HomeCarousel";
import TrendingCarousel from "@/components/TrendingCarousel";
import SectionProduct from "@/components/SectionProduct";
import { getHome } from "@/lib/getHome";

export default function Home({ data }: any) {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-bg">
        <HomeCarousel banners={data.banners} />
        <TrendingCarousel title="Trending Product" products={data.trendingProducts} />
        <SectionProduct title="Featured Product" data={data.featuredProducts} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const data = await getHome();
  return {
    props: {
      data,
    },
  };
}
