import SectionProduct from "@/components/SectionProduct";
import { getTrending } from "@/lib/getTrending";
import Head from "next/head";
import React from "react";

export default function trending({ data }: any) {
  return (
    <>
      <Head>
        <title>Trending Product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-bg">
        <SectionProduct title="Trending Product" data={data} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const data = await getTrending();
  return {
    props: {
      data,
    },
  };
}
